export const ADD_PAINTING_CATEGORY = 'ADD_PAINTING_CATEGORY';

export const REMOVE_PAINTING_CATEGORY = 'REMOVE_PAINTING_CATEGORY';

export const ADD_FURNITURE = 'ADD_FURNITURE';

export const REMOVE_FURNITURE = 'REMOVE_FURNITURE';

export const CHANGE_VALUE = 'CHANGE_VALUE'
